services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - ./data/dragonflydata:/data
# !
# own telegram api server
# needed to download / upload large files
# Container link: https://github.com/aiogram/telegram-bot-api
# Info about limitations: https://core.telegram.org/bots/api#using-a-local-bot-api-server
#
#  telegram-bot-api:
#    image: aiogram/telegram-bot-api:latest
#    environment:
#      TELEGRAM_API_ID: "<api-id>"
#      TELEGRAM_API_HASH: "<api-hash>"
#    volumes:
#      - ./data/telegram-bot-api:/var/lib/telegram-bot-api
#    ports:
#      - "8081:8081"
