services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./data/pocketbase:/pb/pb_data
# !
# own telegram api server
# needed to download / upload large files
# Container link: https://github.com/aiogram/telegram-bot-api
# Info about limitations: https://core.telegram.org/bots/api#using-a-local-bot-api-server
#
#  telegram-bot-api:
#    image: aiogram/telegram-bot-api:latest
#    environment:
#      TELEGRAM_API_ID: "<api-id>"
#      TELEGRAM_API_HASH: "<api-hash>"
#    volumes:
#      - ./data/telegram-bot-api:/var/lib/telegram-bot-api
#    ports:
#      - "8081:8081"
