services:
  face-swap-api:
    build:
      context: .
      dockerfile: Dockerfile-cuda
    environment:
      - DEVICE_TYPE=nvidia
      - THREADS=0
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/temp
      - ./data/models:/app/temp/models
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 