services:
  face-swap-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: apple
    environment:
      - DEVICE_TYPE=apple
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/temp
    security_opt:
      - label=disable
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN 