FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y --allow-change-held-packages \
    python3.10 \
    python3-pip \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    libglx-mesa0 \
    libglvnd0 \
    libglib2.0-0 \
    wget \
    git \
    build-essential \
    cuda-nvrtc-11-8 \
    cuda-cudart-11-8 \
    cuda-libraries-11-8 \
    cuda-libraries-dev-11-8 \
    libcudnn8 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-cuda.txt .
RUN pip3 install --no-cache-dir -r requirements-cuda.txt

WORKDIR /app
COPY . .
RUN mkdir -p temp/models temp/media temp/cache

RUN wget https://huggingface.co/ezioruan/inswapper_128.onnx/resolve/main/inswapper_128.onnx -O temp/models/inswapper_128.onnx

ENV PYTHONUNBUFFERED=1 \
    CUDA_VISIBLE_DEVICES=0 \
    OMP_NUM_THREADS=1 \
    MKL_NUM_THREADS=1 \
    DEVICE_TYPE=cuda \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"] 