name: If it builds, it probably works.

on:
  push:
    branches: [ master, main, '**' ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-face-swap-nvidia:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the face-swap NVIDIA Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker build ./face-swap-component -t ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:latest-nvidia --target nvidia --provenance=false
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker build ./face-swap-component -t ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:$BRANCH_NAME-nvidia --target nvidia --provenance=false
        fi
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the face-swap NVIDIA Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:latest-nvidia
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:$BRANCH_NAME-nvidia
        fi

  build-face-swap-cpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the face-swap CPU Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker build ./face-swap-component -t ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:latest-cpu --provenance=false
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker build ./face-swap-component -t ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:$BRANCH_NAME-cpu --provenance=false
        fi
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the face-swap CPU Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:latest-cpu
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/face-swap:$BRANCH_NAME-cpu
        fi

  build-telegram-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the telegram-bot Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker build ./telegram-bot -t ${{ secrets.REGISTRY }}/${{ github.actor }}/telegram-bot:latest --provenance=false
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker build ./telegram-bot -t ${{ secrets.REGISTRY }}/${{ github.actor }}/telegram-bot:$BRANCH_NAME --provenance=false
        fi
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the telegram-bot Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/telegram-bot:latest
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/telegram-bot:$BRANCH_NAME
        fi

  build-job-manager:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the job-manager Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker build ./job-manager -t ${{ secrets.REGISTRY }}/${{ github.actor }}/job-manager:latest --provenance=false
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker build ./job-manager -t ${{ secrets.REGISTRY }}/${{ github.actor }}/job-manager:$BRANCH_NAME --provenance=false
        fi
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the job-manager Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/job-manager:latest
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/job-manager:$BRANCH_NAME
        fi

  build-pocketbase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the pocketbase Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker build ./pocketbase -t ${{ secrets.REGISTRY }}/${{ github.actor }}/pocketbase:latest --provenance=false
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker build ./pocketbase -t ${{ secrets.REGISTRY }}/${{ github.actor }}/pocketbase:$BRANCH_NAME --provenance=false
        fi
    - uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Push the pocketbase Docker image
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/pocketbase:latest
        else
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          docker push ${{ secrets.REGISTRY }}/${{ github.actor }}/pocketbase:$BRANCH_NAME
        fi