name: If it builds, it probably works.

on:
  push:
  pull_request:
jobs:
  build-telegram-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the telegram-bot Docker image
      run: docker build ./telegram-bot -t telegram-bot:$(date +%s)
  build-job-manager:
    runs-on: ubuntu-latest
    steps:
    - name: Build the job-manager Docker image
      run: docker build ./job-manager -t job-manager:$(date +%s)
  build-pocketbase:
    runs-on: ubuntu-latest
    steps:
    - name: Build the pocketbase Docker image with migrations
      run: docker build ./pocketbase -t pocketbase:$(date +%s)