name: Docker Image CI

on:
  push:
  pull_request:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file telegram-bot/Dockerfile --tag telegram-bot:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file job-manager/Dockerfile --tag job-manager:$(date +%s)
      
