name: Docker Image CI

on:
  push:
  pull_request:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./telegram-bot -t telegram-bot:$(date +%s)
    - name: Build the Docker image
      run: docker build ./job-manager -t job-manager:$(date +%s)
      
